### ISSUE TITLE
Remove CI integration

### ISSUE THREAD

**Issue by rudolf-adamkovic** [eggheadgames/aws-sdk-ios-mobileanalytics#10]
Blocking #9

There is nothing to integrate here.

**Comment by mikemee** [comment]
Already done (just a few mins before - great minds think alike 👍 )

**Comment by rudolf-adamkovic** [comment]
Not done yet:

<img width="690" alt="screen shot 2017-06-01 at 15 57 56" src="https://cloud.githubusercontent.com/assets/1158274/26683138/21cd1340-46e3-11e7-8b69-f01988ca41a9.png">

**Comment by mikemee** [comment]
That was github getting caught up. With the last push to #9 , that seems to have resolved: 

![2017-06-01_07-03-28_01](https://cloud.githubusercontent.com/assets/550990/26683374/70486452-4698-11e7-8524-c31c5d264caa.png)

**Comment by rudolf-adamkovic** [comment]
@mikemee 

> That was github getting caught up.

👍

P.S. GitHub is a proper ... never mind. 😡
