### ISSUE TITLE
Simplify repository name

### ISSUE THREAD

**Issue by rudolf-adamkovic** [eggheadgames/aws-sdk-ios-mobileanalytics#5]
We don't need to say both "iOS" and "Mobile". For example, `amazon-ios-analytics` would be 25% less characters. Also more readable. Alternatively `aws-ios-analytics`.

CC: @lauracalinoiu

**Comment by mikemee** [comment]
I agree. However I intentionally made this match the amazon nomenclature so that perhaps other people might find it when they search GitHub.
